# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 17:16
from __future__ import unicode_literals

import apps.utils.images
import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.CharField(blank=True, editable=False, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('description', models.TextField()),
                ('logo', sorl.thumbnail.fields.ImageField(upload_to=apps.utils.images.logo_upload_path)),
                ('dissolution_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
